### PR TITLE
Allow changing branch name

### PR DESCRIPTION
**Pull request by ruudk**
I'm using `main` instead of `master`.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi @ruudk, thanks for contributions!

I wish GitHub added option to disable pull-requests. This just a split package.

Could I hubmly to ask you to move contributions to a monorepo  https://github.com/symplify/github-actions?

I've checked all your contributions and they're needed! Feel free to send it as 1 pull-requests.

**Comment by ruudk** [comment]
Haha, I feel stupid now 🙈 

Could you please add something like `[READ ONLY] ` prefix to all the descriptions of the repositories? 

It might be an idea to also setup a PR Github Template that says "Don't create your PR here, but at the mono". I'm going to also implement that (since I will get the same problems on my mono repo). 

I will provide a new PR later.

**Comment by TomasVotruba** [comment]
> Haha, I feel stupid now see_no_evil

No need to. It's bad design choice of Github for repositories.

> It might be an idea to also setup a PR Github Template that says "Don't create your PR here, but at the mono". I'm going to also implement that (since I will get the same problems on my mono repo).

That could be a nice packages. I'd use it at least in 50 of my packages :D.

---

> I will provide a new PR later.

I'm going to publish a post about this package and basically I'm waiting for your PRs to get merged so people get the best version :D 
Are you able to do it in 2-3 hours?

**Comment by ruudk** [comment]
@TomasVotruba On it! I will also create some issues that I noticed while implementing this.

**Pull request closed without merging**
